name: dappstore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  flutter_injected_web3:
    git:
      url: https://github.com/Orange-Wallet/flutter_injected_web3
      ref: dde6c3301fae6f7ca4cebe20fd8ebb3500d23fe2
  flutter_inappwebview: ^5.7.1
  injectable: ^2.1.0
  dio_cache_interceptor: ^3.4.0
  get_it: ^7.2.0
  bloc: ^8.1.1
  flutter_downloader:
    git:
      url: https://github.com/Abhimanyu121/flutter_downloader
      ref: 5793a503cbcf3c9564add296de075052f40e66fc
  android_path_provider: ^0.3.0
  device_info_plus: ^8.1.0
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  installed_apps: ^1.3.1
  wallet_connect_dart_v2: ^0.0.1
  url_launcher: ^6.1.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  android_intent_plus: ^3.1.6
  flutter_localization: ^0.1.10
  intl: ^0.17.0
  flutter_app_installer:
    git:
      url: https://github.com/Abhimanyu121/flutter-app-installer
      ref: 052cb4e0760771a4c900e10930eb42c2abbaa372
  cached_network_image: ^3.2.3
  shimmer_animation: ^2.1.0+1
  jovial_svg: 1.1.9
  flutter_rating_bar: ^4.0.1
  eth_sig_util: ^0.0.9
  sentry_flutter: ^7.3.0
  readmore: ^2.1.0
  responsive_framework: ^0.2.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.2.1
  flutter_native_splash: 2.2.17
  package_info_plus: ^3.0.3
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter_phoenix: 1.1.0
  internet_connection_checker: ^1.0.0+1
  random_avatar: ^0.0.7
  version: ^3.0.2
  permission_handler_platform_interface: ^3.9.0
  notification_permissions: ^0.6.1
  flutter_displaymode: ^0.5.0

# dependency_overrides:
  # stream_channel: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/GeneralSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/GeneralSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeneralSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/GeneralSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GeneralSans-MediumItalic.ttf
          weight: 500

flutter_native_splash:
  color: "#000000"
  image: assets/images/slick_logo_transparent.png
  branding: assets/images/slick_logo_transparent.png
  image_dark: assets/images/slick_logo_transparent.png
  branding_dark: assets/images/slick_logo_transparent.png

  android_12:
    image: assets/images/slick_logo_transparent.png
    icon_background_color: "#000000"
    image_dark: assets/images/slick_logo_transparent.png
    icon_background_color_dark: "#000000"

  web: false